version: '3.7'
networks:
  tests:
    name: tests
services:
  redis:
    hostname: redis
    image: bradrydzewski/redis:2.8
    networks:
    - tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    init: true
    depends_on:
    - redis
    environment:
      GIT_BRANCH: ${CI_COMMIT_REF_NAME:-master}
    volumes:
      - .:${MOUNT_PATH:-/gc/penalty-box}
    env_file:
      - ./env/integration.env
    command: make install test
    networks:
    - tests
    working_dir: /gc/penalty-box
